#!/usr/bin/env bash

ANDROID_WINDOWS_WORKDIR_DEFAULT='C:\dev\foliole-android-preview'
ANDROID_WINDOWS_WORKDIR="${ANDROID_WINDOWS_WORKDIR:-${ANDROID_WINDOWS_WORKDIR_DEFAULT}}"
ANDROID_WINDOWS_MIRROR_DIR="${ANDROID_WINDOWS_MIRROR_DIR:-$(wslpath -u "${ANDROID_WINDOWS_WORKDIR}")}"
