#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export ANDROID_PREVIEW_OPEN_STUDIO="${ANDROID_PREVIEW_OPEN_STUDIO:-0}"
export ANDROID_GRADLE_STOP_AFTER_DEPLOY="${ANDROID_GRADLE_STOP_AFTER_DEPLOY:-1}"
export ANDROID_WINDOWS_DEPENDENCY_REFRESH="${ANDROID_WINDOWS_DEPENDENCY_REFRESH:-skip}"

exec bash "${SCRIPT_DIR}/android-preview.sh"
