import { FOLDER_TOPIC_ITEM_APP_COMMAND_IDS } from '../../../lib/core/nodes/folderTopicItemCommands';
import { VIRTUAL_NODE_APP_COMMAND_ID } from '../../../lib/core/nodes/virtualNodeCommands';

export const APP_COMMAND_IDS = {
  toggleCommandPaletteMac: 'commandPalette.toggle.mac',
  toggleCommandPaletteWin: 'commandPalette.toggle.win',
  closeCommandPalette: 'ui.closeCommandPalette',
  closeSettings: 'ui.closeSettings',
  closeContextMenu: 'ui.closeContextMenu',
  undo: 'app.undo',
  redo: 'app.redo',
  goBack: 'navigation.goBack',
  goForward: 'navigation.goForward',
  goToNode: 'navigation.goToNode',
  moveToNode: 'navigation.moveToNode',
  renameNode: 'workspace.renameNode',
  findInTopic: 'document.findInTopic',
  enterPriorityMode: 'nodes.enterPriorityMode',
  mergeHighlightsIntoTopic: 'workspace.mergeHighlightsIntoTopic',
  createSelectionHighlight: 'editor.createSelectionHighlight',
  createSelectionCloze: 'editor.createSelectionCloze',
  addSelectionNote: 'editor.addSelectionNote',
  repairTable: 'editor.repairTable',
  goParent: 'navigation.goParent',
  toggleEditorDisplayMode: 'editor.toggleDisplayMode',
  toggleImmersiveMode: 'editor.toggleImmersiveMode',
  toggleDismissedTopicsVisibility: 'view.toggleDismissedTopicsVisibility',
  startStudyMode: 'review.startStudyMode',
  revealReviewAnswer: 'review.revealAnswer',
  gradeReviewAgain: 'review.gradeAgain',
  gradeReviewHard: 'review.gradeHard',
  gradeReviewGood: 'review.gradeGood',
  gradeReviewEasy: 'review.gradeEasy',
  readingReviewSoon: 'review.readingSoon',
  readingReviewLater: 'review.readingLater',
  readingReviewPostpone: 'review.readingPostpone',
  readingReviewRead: 'review.readingRead',
  readingReviewDismiss: 'review.readingDismiss',
  reviewScrollReadingDown: 'review.scrollReadingDown',
  reviewScrollReadingUp: 'review.scrollReadingUp',
  deleteCurrentReviewItem: 'review.deleteCurrentItem',
  reviewNavigateParent: 'review.navigateParent',
  reviewNavigateBack: 'review.navigateBack',
  reviewNavigateForward: 'review.navigateForward',
  reviewNavigateDown: 'review.navigateDown',
  reviewNavigatePreviousSibling: 'review.navigatePreviousSibling',
  reviewNavigateNextSibling: 'review.navigateNextSibling',
  deleteReviewSourceTopic: 'review.deleteSourceTopic',
  importSingleFile: 'import.singleFileToInbox',
  importFolder: 'import.folderToInbox',
  clipboardImport: 'import.clipboard',
  openImportManagement: 'import.openManagement',
  resetImportData: 'dev.resetImportData',
  reimportSelectedTopic: 'dev.reimportSelectedTopic',
  toggleDevReviewStatusBarPersistence: 'dev.toggleReviewStatusBarPersistence',
  openNotes: 'workspace.openNotes',
  openHelpSearch: 'workspace.openHelpSearch',
  openTrash: 'workspace.openTrash',
  createFolder: FOLDER_TOPIC_ITEM_APP_COMMAND_IDS.createFolder,
  createTopic: FOLDER_TOPIC_ITEM_APP_COMMAND_IDS.createTopic,
  createItem: FOLDER_TOPIC_ITEM_APP_COMMAND_IDS.createItem,
  createVirtualNode: VIRTUAL_NODE_APP_COMMAND_ID,
  openSettings: 'workspace.openSettings',
  openReadwiseReaderSettings: 'workspace.openReadwiseReaderSettings',
  toggleBaseColorMode: 'settings.toggleBaseColorMode',
  setPdfDarkAppearanceOriginal: 'settings.setPdfDarkAppearance.original',
  setPdfDarkAppearanceInverted: 'settings.setPdfDarkAppearance.inverted',
  setPdfDarkAppearanceWarm: 'settings.setPdfDarkAppearance.warm',
  exportCurrentArticle: 'workspace.exportCurrentArticle',
  restartApp: 'workspace.restartApp',
  toggleList: 'workspace.toggleList',
  toggleRightSidebar: 'workspace.toggleRightSidebar',
  toggleBothSidebars: 'workspace.toggleBothSidebars',
  toggleDevTools: 'workspace.toggleDevTools'
} as const;

export type AppCommandId = (typeof APP_COMMAND_IDS)[keyof typeof APP_COMMAND_IDS];
