import { FOLDER_TOPIC_ITEM_APP_COMMAND_IDS } from '../../../lib/core/nodes/folderTopicItemCommands';
import { VIRTUAL_NODE_APP_COMMAND_ID } from '../../../lib/core/nodes/virtualNodeCommands';

export const APP_COMMAND_IDS = {
  toggleCommandPaletteMac: 'commandPalette.toggle.mac',
  toggleCommandPaletteWin: 'commandPalette.toggle.win',
  closeCommandPalette: 'ui.closeCommandPalette',
  closeSettings: 'ui.closeSettings',
  closeContextMenu: 'ui.closeContextMenu',
  goBack: 'navigation.goBack',
  goForward: 'navigation.goForward',
  goToNode: 'navigation.goToNode',
  moveToNode: 'navigation.moveToNode',
  findInTopic: 'document.findInTopic',
  enterPriorityMode: 'nodes.enterPriorityMode',
  mergeHighlightsIntoTopic: 'workspace.mergeHighlightsIntoTopic',
  goParent: 'navigation.goParent',
  toggleEditorDisplayMode: 'editor.toggleDisplayMode',
  toggleImmersiveMode: 'editor.toggleImmersiveMode',
  startStudyMode: 'review.startStudyMode',
  revealReviewAnswer: 'review.revealAnswer',
  gradeReviewAgain: 'review.gradeAgain',
  gradeReviewHard: 'review.gradeHard',
  gradeReviewGood: 'review.gradeGood',
  gradeReviewEasy: 'review.gradeEasy',
  readingReviewLater: 'review.readingLater',
  readingReviewRead: 'review.readingRead',
  readingReviewDismiss: 'review.readingDismiss',
  importSingleFile: 'import.singleFileToInbox',
  importFolder: 'import.folderToInbox',
  clipboardImport: 'import.clipboard',
  openImportManagement: 'import.openManagement',
  resetImportData: 'dev.resetImportData',
  openNotes: 'workspace.openNotes',
  openTrash: 'workspace.openTrash',
  createFolder: FOLDER_TOPIC_ITEM_APP_COMMAND_IDS.createFolder,
  createTopic: FOLDER_TOPIC_ITEM_APP_COMMAND_IDS.createTopic,
  createItem: FOLDER_TOPIC_ITEM_APP_COMMAND_IDS.createItem,
  createVirtualNode: VIRTUAL_NODE_APP_COMMAND_ID,
  openSettings: 'workspace.openSettings',
  openReadwiseReaderSettings: 'workspace.openReadwiseReaderSettings',
  toggleBaseColorMode: 'settings.toggleBaseColorMode',
  exportCurrentArticle: 'workspace.exportCurrentArticle',
  restartApp: 'workspace.restartApp',
  toggleList: 'workspace.toggleList',
  toggleDevTools: 'workspace.toggleDevTools'
} as const;

export type AppCommandId = (typeof APP_COMMAND_IDS)[keyof typeof APP_COMMAND_IDS];
