import type { AppLocale } from './appLanguage';

export interface SystemEntryLocalizationContract {
  system: readonly string[];
  desktop: readonly string[];
  demo: readonly string[];
  tabs: readonly string[];
  shortcuts: readonly string[];
  groups: readonly string[];
}

export const SYSTEM_ENTRY_LOCALIZATION_CONTRACT = {
  en: { system: ['Home', 'Inbox', 'Trash', 'Virtual folders', 'Published', 'Shelved', 'Removed'], desktop: ['Import', 'Import Clipboard', 'Reading Mode', 'Search', 'Command Palette', 'Send Feedback', 'Appearance Mode', 'Study', 'Settings'], demo: ['Language', 'Home', 'Download app', 'Send Feedback', 'Reset data'], tabs: ['Browse', 'Flow', 'Search', 'Settings'], shortcuts: ['Directory', 'Only Review', 'Sync', 'Tabs', 'Sync Activity', 'Sync Connection', 'Handoff reminders'], groups: ['External', 'Virtual folders', 'Trash'] },
  de: { system: ['Start', 'Eingang', 'Papierkorb', 'Virtuelle Ordner', 'Veröffentlicht', 'Zurückgestellt', 'Entfernt'], desktop: ['Importieren', 'Zwischenablage importieren', 'Lesemodus', 'Suchen', 'Befehlspalette', 'Feedback senden', 'Darstellungsmodus', 'Lernen', 'Einstellungen'], demo: ['Sprache', 'Startseite', 'App herunterladen', 'Feedback senden', 'Daten zurücksetzen'], tabs: ['Durchsuchen', 'Flow', 'Suchen', 'Einstellungen'], shortcuts: ['Verzeichnis', 'Nur Wiederholen', 'Synchronisieren', 'Tabs', 'Synchronisierungsaktivität', 'Synchronisierungsverbindung', 'Übergabeerinnerungen'], groups: ['Extern', 'Virtuelle Ordner', 'Papierkorb'] },
  es: { system: ['Inicio', 'Bandeja de entrada', 'Papelera', 'Carpetas virtuales', 'Publicados', 'Aplazados', 'Retirados'], desktop: ['Importar', 'Importar desde el portapapeles', 'Modo de lectura', 'Buscar', 'Paleta de comandos', 'Enviar comentarios', 'Modo de apariencia', 'Estudiar', 'Configuración'], demo: ['Idioma', 'Inicio', 'Descargar aplicación', 'Enviar comentarios', 'Restablecer datos'], tabs: ['Explorar', 'Flow', 'Buscar', 'Configuración'], shortcuts: ['Directorio', 'Solo repaso', 'Sincronizar', 'Pestañas', 'Actividad de sincronización', 'Conexión de sincronización', 'Recordatorios de transferencia'], groups: ['Externo', 'Carpetas virtuales', 'Papelera'] },
  fr: { system: ['Accueil', 'Boîte de réception', 'Corbeille', 'Dossiers virtuels', 'Publiés', 'En attente', 'Retirés'], desktop: ['Importer', 'Importer le presse-papiers', 'Mode lecture', 'Rechercher', 'Palette de commandes', 'Envoyer des commentaires', 'Mode d’apparence', 'Étudier', 'Paramètres'], demo: ['Langue', 'Accueil', 'Télécharger l’application', 'Envoyer des commentaires', 'Réinitialiser les données'], tabs: ['Parcourir', 'Flow', 'Rechercher', 'Paramètres'], shortcuts: ['Répertoire', 'Révision uniquement', 'Synchroniser', 'Onglets', 'Activité de synchronisation', 'Connexion de synchronisation', 'Rappels de transfert'], groups: ['Externe', 'Dossiers virtuels', 'Corbeille'] },
  it: { system: ['Inizio', 'Posta in arrivo', 'Cestino', 'Cartelle virtuali', 'Pubblicati', 'Accantonati', 'Rimossi'], desktop: ['Importa', 'Importa dagli appunti', 'Modalità lettura', 'Cerca', 'Tavolozza comandi', 'Invia feedback', 'Modalità aspetto', 'Studia', 'Impostazioni'], demo: ['Lingua', 'Inizio', 'Scarica l’app', 'Invia feedback', 'Reimposta i dati'], tabs: ['Sfoglia', 'Flow', 'Cerca', 'Impostazioni'], shortcuts: ['Indice', 'Solo ripasso', 'Sincronizza', 'Schede', 'Attività di sincronizzazione', 'Connessione di sincronizzazione', 'Promemoria di passaggio'], groups: ['Esterno', 'Cartelle virtuali', 'Cestino'] },
  ja: { system: ['ホーム', '受信トレイ', 'ゴミ箱', '仮想フォルダ', '公開済み', '保留', '削除済み'], desktop: ['インポート', 'クリップボードからインポート', '読書モード', '検索', 'コマンドパレット', 'フィードバックを送信', '外観モード', '学習', '設定'], demo: ['言語', '公式サイト', 'アプリをダウンロード', 'フィードバックを送信', 'データをリセット'], tabs: ['閲覧', 'Flow', '検索', '設定'], shortcuts: ['ディレクトリ', '復習のみ', '同期', 'タブ', '同期履歴', '同期接続', '引き継ぎリマインダー'], groups: ['外部', '仮想フォルダ', 'ゴミ箱'] },
  ko: { system: ['홈', '받은 편지함', '휴지통', '가상 폴더', '게시됨', '보류됨', '제거됨'], desktop: ['가져오기', '클립보드에서 가져오기', '읽기 모드', '검색', '명령 팔레트', '피드백 보내기', '화면 모드', '학습', '설정'], demo: ['언어', '공식 사이트', '앱 다운로드', '피드백 보내기', '데이터 재설정'], tabs: ['탐색', 'Flow', '검색', '설정'], shortcuts: ['디렉터리', '복습만', '동기화', '탭', '동기화 활동', '동기화 연결', '이어받기 알림'], groups: ['외부', '가상 폴더', '휴지통'] },
  pl: { system: ['Start', 'Skrzynka odbiorcza', 'Kosz', 'Foldery wirtualne', 'Opublikowane', 'Odłożone', 'Usunięte'], desktop: ['Importuj', 'Importuj ze schowka', 'Tryb czytania', 'Szukaj', 'Paleta poleceń', 'Wyślij opinię', 'Tryb wyglądu', 'Nauka', 'Ustawienia'], demo: ['Język', 'Strona główna', 'Pobierz aplikację', 'Wyślij opinię', 'Zresetuj dane'], tabs: ['Przeglądaj', 'Flow', 'Szukaj', 'Ustawienia'], shortcuts: ['Katalog', 'Tylko powtórki', 'Synchronizuj', 'Karty', 'Aktywność synchronizacji', 'Połączenie synchronizacji', 'Przypomnienia o przekazaniu'], groups: ['Zewnętrzne', 'Foldery wirtualne', 'Kosz'] },
  'pt-BR': { system: ['Início', 'Caixa de entrada', 'Lixeira', 'Pastas virtuais', 'Publicados', 'Em espera', 'Removidos'], desktop: ['Importar', 'Importar da área de transferência', 'Modo de leitura', 'Pesquisar', 'Paleta de comandos', 'Enviar feedback', 'Modo de aparência', 'Estudar', 'Configurações'], demo: ['Idioma', 'Início', 'Baixar aplicativo', 'Enviar feedback', 'Redefinir dados'], tabs: ['Navegar', 'Flow', 'Pesquisar', 'Configurações'], shortcuts: ['Diretório', 'Somente revisão', 'Sincronizar', 'Abas', 'Atividade de sincronização', 'Conexão de sincronização', 'Lembretes de transferência'], groups: ['Externo', 'Pastas virtuais', 'Lixeira'] },
  ru: { system: ['Главная', 'Входящие', 'Корзина', 'Виртуальные папки', 'Опубликованные', 'Отложенные', 'Удалённые'], desktop: ['Импорт', 'Импорт из буфера обмена', 'Режим чтения', 'Поиск', 'Палитра команд', 'Отправить отзыв', 'Режим оформления', 'Учёба', 'Настройки'], demo: ['Язык', 'Главная', 'Скачать приложение', 'Отправить отзыв', 'Сбросить данные'], tabs: ['Обзор', 'Flow', 'Поиск', 'Настройки'], shortcuts: ['Каталог', 'Только повторение', 'Синхронизация', 'Вкладки', 'Активность синхронизации', 'Подключение синхронизации', 'Напоминания о передаче'], groups: ['Внешнее', 'Виртуальные папки', 'Корзина'] },
  'zh-Hans': { system: ['Home', '收件箱', '回收站', '虚拟文件夹', '发布', '搁置', '移除'], desktop: ['导入', '从剪贴板导入', '阅读模式', '搜索', '命令面板', '发送反馈', '外观模式', '学习', '设置'], demo: ['语言', '官网', '下载应用', '发送反馈', '重置数据'], tabs: ['浏览', 'Flow', '搜索', '设置'], shortcuts: ['目录', '仅复习', '同步', '标签页', '同步活动', '同步连接', '接力提醒'], groups: ['外部', '虚拟文件夹', '回收站'] },
  'zh-Hant': { system: ['Home', '收件匣', '垃圾桶', '虛擬資料夾', '發佈', '擱置', '移除'], desktop: ['匯入', '從剪貼簿匯入', '閱讀模式', '搜尋', '命令面板', '傳送回饋', '外觀模式', '學習', '設定'], demo: ['語言', '官網', '下載應用程式', '傳送回饋', '重置資料'], tabs: ['瀏覽', 'Flow', '搜尋', '設定'], shortcuts: ['目錄', '僅複習', '同步', '標籤頁', '同步活動', '同步連線', '接力提醒'], groups: ['外部', '虛擬資料夾', '垃圾桶'] }
} satisfies Record<AppLocale, SystemEntryLocalizationContract>;
