import { ANDROID_COMPANION_PAYLOAD_QUERY_DEFINITIONS } from './androidCompanionPayloadQueryDefinitions.ts';
import { ANDROID_COMPANION_RESOURCE_QUERY_DEFINITIONS } from './androidCompanionResourceQueryDefinitions.ts';
import { ANDROID_COMPANION_SYNC_QUERY_DEFINITIONS } from './androidCompanionSyncQueryDefinitions.ts';

export const ANDROID_COMPANION_QUERY_DEFINITIONS = {
  ...ANDROID_COMPANION_SYNC_QUERY_DEFINITIONS,
  ...ANDROID_COMPANION_RESOURCE_QUERY_DEFINITIONS,
  ...ANDROID_COMPANION_PAYLOAD_QUERY_DEFINITIONS
};
