export const ANDROID_COMPANION_RESOURCE_SCHEMA_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS attachment_blobs (
    attachment_id TEXT PRIMARY KEY,
    content_hash TEXT,
    storage_key TEXT,
    size_bytes INTEGER,
    mime_type TEXT,
    availability TEXT NOT NULL DEFAULT 'missing',
    source_device_id TEXT,
    created_at TEXT NOT NULL,
    cached_at TEXT,
    last_verified_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS content_blobs (
    hash TEXT PRIMARY KEY,
    storage_key TEXT NOT NULL,
    kind TEXT NOT NULL,
    mime_type TEXT,
    compression TEXT NOT NULL DEFAULT 'none',
    original_size_bytes INTEGER NOT NULL,
    stored_size_bytes INTEGER NOT NULL,
    original_sha256 TEXT NOT NULL,
    stored_sha256 TEXT NOT NULL,
    availability TEXT NOT NULL DEFAULT 'missing',
    source_device_id TEXT,
    created_at TEXT NOT NULL,
    cached_at TEXT,
    last_verified_at TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS idx_content_blobs_availability
    ON content_blobs (availability)`,
  `CREATE INDEX IF NOT EXISTS idx_content_blobs_kind
    ON content_blobs (kind)`,
  `CREATE TABLE IF NOT EXISTS content_blob_data (
    hash TEXT PRIMARY KEY,
    data BLOB NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS pdf_page_text (
    attachment_id TEXT NOT NULL,
    page INTEGER NOT NULL,
    text TEXT NOT NULL,
    page_width REAL,
    page_height REAL,
    PRIMARY KEY (attachment_id, page)
  )`,
  `CREATE TABLE IF NOT EXISTS import_sources (
    source_fingerprint TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    source_kind TEXT NOT NULL,
    source_name TEXT NOT NULL,
    source_locator TEXT NOT NULL,
    first_imported_at TEXT NOT NULL,
    last_imported_at TEXT NOT NULL,
    last_content_fingerprint TEXT NOT NULL,
    latest_node_id TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS external_search_folders (
    id TEXT PRIMARY KEY,
    folder_path TEXT NOT NULL UNIQUE,
    attachment_mode TEXT NOT NULL,
    attachment_root_path TEXT,
    excluded_dirs_json TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'idle',
    document_count INTEGER NOT NULL DEFAULT 0,
    indexed_at TEXT,
    last_error TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS external_documents (
    document_id TEXT PRIMARY KEY,
    folder_id TEXT NOT NULL,
    relative_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    extension TEXT NOT NULL,
    source_size_bytes INTEGER NOT NULL,
    source_modified_at TEXT NOT NULL,
    source_modified_ms INTEGER NOT NULL,
    content_hash TEXT NOT NULL,
    title TEXT,
    opening_text TEXT,
    body_blob_hash TEXT,
    content TEXT NOT NULL,
    indexed_at TEXT NOT NULL,
    is_present INTEGER NOT NULL DEFAULT 1,
    missing_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS readwise_sources (
    source_id TEXT PRIMARY KEY,
    reader_document_id TEXT NOT NULL,
    readwise_book_id TEXT,
    title TEXT NOT NULL DEFAULT '',
    author TEXT,
    category TEXT,
    location TEXT,
    tags_json TEXT NOT NULL DEFAULT '[]',
    source_url TEXT,
    raw_source_url TEXT,
    raw_source_url_status TEXT NOT NULL DEFAULT 'unknown',
    remote_updated_at TEXT,
    sync_cursor TEXT,
    sync_status TEXT NOT NULL DEFAULT 'idle',
    source_state TEXT NOT NULL DEFAULT 'external',
    promotion_lock INTEGER NOT NULL DEFAULT 0,
    internal_node_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    UNIQUE(reader_document_id)
  )`,
  `CREATE TABLE IF NOT EXISTS readwise_source_annotations (
    source_id TEXT NOT NULL,
    readwise_book_id TEXT NOT NULL,
    highlight_id TEXT NOT NULL,
    reader_document_id TEXT NOT NULL,
    parent_id TEXT,
    annotation_kind TEXT NOT NULL DEFAULT 'highlight',
    text TEXT,
    note TEXT,
    location TEXT,
    remote_updated_at TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    PRIMARY KEY (readwise_book_id, highlight_id)
  )`
];
