package com.foliole.android;

final class FolioleCompanionResourceQueryStringKeys {
    private FolioleCompanionResourceQueryStringKeys() {}

    static String string(String section, String group, String key) {
        switch (section + "." + group + "." + key) {
            case "contentRead.groupKeys.externalDocuments": return "externalDocuments";
            case "contentRead.groupKeys.readableArticle": return "readableArticle";
            case "contentRead.externalDocuments.byIdQueryName": return "externalDocumentById";
            case "contentRead.externalDocuments.directoryEntriesQueryName": return "externalDocumentDirectoryEntries";
            case "contentRead.externalDocuments.directoryEntriesResultKey": return "entries";
            case "contentRead.externalDocuments.documentResultKey": return "document";
            case "contentRead.externalDocuments.documentsResultKey": return "documents";
            case "contentRead.externalDocuments.foldersQueryName": return "externalSearchFolders";
            case "contentRead.externalDocuments.foldersResultKey": return "folders";
            case "contentRead.externalDocuments.searchQueryName": return "externalDocumentSearch";
            case "contentRead.externalDocuments.searchResultsKey": return "results";
            case "contentRead.readableArticle.activeNodeIdQueryName": return "readableArticleActiveNodeId";
            case "contentRead.readableArticle.articleResultKey": return "readable_article";
            case "contentRead.readableArticle.articlesResultKey": return "articles";
            case "contentRead.readableArticle.byNodeIdQueryName": return "readableArticleByNodeId";
            case "contentRead.readableArticle.firstNodeQueryName": return "readableArticleFirstNode";
            case "contentRead.readableArticle.pdfPagesQueryName": return "pdfPageTextPages";
            case "contentRead.readableArticle.pdfPagesResultKey": return "pages";
            case "contentRead.readableArticle.pdfPlaceholderText": return "Linked PDF source ready for the reader surface.";
            case "contentRead.readableArticle.referencePdfAttachmentQueryName": return "readableArticleReferencePdfAttachment";
            case "contentRead.readableArticle.untitledTitle": return "Untitled";
            case "missingResourceRead.groupKeys.attachmentResources": return "attachmentResources";
            case "missingResourceRead.groupKeys.contentBlobs": return "contentBlobs";
            case "missingResourceRead.attachmentResources.byIdQueryName": return "attachmentResourceMissingById";
            case "missingResourceRead.attachmentResources.emptyResultKey": return "resource";
            case "missingResourceRead.attachmentResources.resultKey": return "resources";
            case "missingResourceRead.attachmentResources.rowsQueryName": return "attachmentResourceMissingRows";
            case "missingResourceRead.attachmentResources.summaryQueryName": return "attachmentResourceMissingSummaryRows";
            case "missingResourceRead.contentBlobs.hashKey": return "hash";
            case "missingResourceRead.contentBlobs.hashesResultKey": return "hashes";
            case "missingResourceRead.contentBlobs.hashesQueryName": return "contentBlobMissingHashes";
            case "missingResourceRead.contentBlobs.resultKey": return "blobs";
            case "missingResourceRead.contentBlobs.summaryQueryName": return "contentBlobMissingSummaryRows";
            case "resourceRead.groupKeys.attachmentResources": return "attachmentResources";
            case "resourceRead.groupKeys.contentBlobCas": return "contentBlobCas";
            case "resourceRead.groupKeys.contentBlobs": return "contentBlobs";
            case "resourceRead.groupKeys.pdfPageText": return "pdfPageText";
            case "resourceRead.attachmentResources.attachmentIdKey": return "attachment_id";
            case "resourceRead.attachmentResources.contentHashKey": return "content_hash";
            case "resourceRead.attachmentResources.contentHashesByIdsQueryName": return "attachmentResourceContentHashesByIds";
            case "resourceRead.attachmentResources.contentHashesReplacement": return "__ATTACHMENT_ID_FILTER__";
            case "resourceRead.attachmentResources.directoryName": return "attachments";
            case "resourceRead.attachmentResources.mimeTypeKey": return "mime_type";
            case "resourceRead.attachmentResources.resolveQueryName": return "attachmentResourceResolve";
            case "resourceRead.attachmentResources.resultKey": return "resources";
            case "resourceRead.attachmentResources.storageKey": return "storage_key";
            case "resourceRead.contentBlobs.compressionKey": return "compression";
            case "resourceRead.contentBlobs.dataTableName": return "content_blob_data";
            case "resourceRead.contentBlobs.existingQueryName": return "contentBlobDataExisting";
            case "resourceRead.contentBlobs.hashKey": return "hash";
            case "resourceRead.contentBlobs.hashesReplacement": return "__HASH_FILTER__";
            case "resourceRead.contentBlobs.manifestTableName": return "content_blobs";
            case "resourceRead.contentBlobs.manifestsByHashesQueryName": return "contentBlobManifestsByHashes";
            case "resourceRead.contentBlobs.manifestQueryName": return "contentBlobManifestByHash";
            case "resourceRead.contentBlobs.originalSha256Key": return "original_sha256";
            case "resourceRead.contentBlobs.originalSizeBytesKey": return "original_size_bytes";
            case "resourceRead.contentBlobs.resultKey": return "blobs";
            case "resourceRead.contentBlobs.storedSha256Key": return "stored_sha256";
            case "resourceRead.contentBlobs.storedSizeBytesKey": return "stored_size_bytes";
            case "resourceRead.contentBlobCas.hashAlgorithm": return "SHA-256";
            case "resourceRead.contentBlobCas.hashPattern": return "^[a-f0-9]{64}$";
            case "resourceRead.contentBlobCas.supportedCompression": return "none";
            case "resourceRead.pdfPageText.attachmentIdKey": return "attachment_id";
            case "resourceRead.pdfPageText.matchIndexKey": return "match_index";
            case "resourceRead.pdfPageText.pageHeightKey": return "page_height";
            case "resourceRead.pdfPageText.pageKey": return "page";
            case "resourceRead.pdfPageText.pagesQueryName": return "pdfPageTextPages";
            case "resourceRead.pdfPageText.pagesResultKey": return "pages";
            case "resourceRead.pdfPageText.pageWidthKey": return "page_width";
            case "resourceRead.pdfPageText.searchQueryName": return "pdfPageTextSearch";
            case "resourceRead.pdfPageText.searchResultKey": return "results";
            case "resourceRead.pdfPageText.textKey": return "text";
            case "workspaceRead.groupKeys.snapshot": return "snapshot";
            case "workspaceRead.groupKeys.viewState": return "viewState";
            case "workspaceRead.snapshot.bodyStatusExpressionToken": return "__BODY_STATUS_EXPRESSION__";
            case "workspaceRead.snapshot.bodyStatusExpressionInlineSql": return "CASE WHEN TRIM(COALESCE(n.content, '')) = '' THEN 'empty' ELSE 'ready' END";
            case "workspaceRead.snapshot.bodyStatusExpressionWithBodyBlobSql": return "CASE WHEN n.body_blob_hash IS NOT NULL AND TRIM(n.body_blob_hash) <> '' AND CAST(cbd.data AS TEXT) IS NULL THEN CASE WHEN cb.availability IN ('fetching', 'failed') THEN cb.availability ELSE 'missing' END WHEN TRIM(COALESCE(COALESCE(CAST(cbd.data AS TEXT), n.content), '')) = '' THEN 'empty' ELSE 'ready' END";
            case "workspaceRead.snapshot.contentBlobJoinToken": return "__CONTENT_BLOB_JOIN__";
            case "workspaceRead.snapshot.contentBlobJoinSql": return "LEFT JOIN content_blobs cb ON cb.hash = n.body_blob_hash LEFT JOIN content_blob_data cbd ON cbd.hash = n.body_blob_hash ";
            case "workspaceRead.snapshot.contentExpressionToken": return "__CONTENT_EXPRESSION__";
            case "workspaceRead.snapshot.contentExpressionInlineSql": return "n.content";
            case "workspaceRead.snapshot.contentExpressionWithBodyBlobSql": return "COALESCE(CAST(cbd.data AS TEXT), n.content)";
            case "workspaceRead.snapshot.deletedAtRowKey": return "deleted_at";
            case "workspaceRead.snapshot.nodeIdRowKey": return "id";
            case "workspaceRead.snapshot.metaValueQueryName": return "workspaceMetaValue";
            case "workspaceRead.snapshot.metaValueResultKey": return "rows";
            case "workspaceRead.snapshot.nodesQueryName": return "workspaceSnapshotNodes";
            case "workspaceRead.snapshot.nodesResultKey": return "nodes";
            case "workspaceRead.snapshot.orderedNodeIdsQueryName": return "workspaceOrderedNodeIds";
            case "workspaceRead.snapshot.orderedNodeIdsResultKey": return "nodes";
            case "workspaceRead.snapshot.untitledSequenceMetaKey": return "untitled_sequence_by_parent";
            case "workspaceRead.viewState.defaultSource": return "user-scroll";
            case "workspaceRead.viewState.nodeIdRowKey": return "node_id";
            case "workspaceRead.viewState.queryName": return "nodeViewStatesByDevice";
            case "workspaceRead.viewState.resultKey": return "states";
            default: throw new IllegalStateException("Companion resource query descriptor is missing string key: " + section + "." + group + "." + key);
        }
    }

    static String nestedString(String section, String group, String object, String key) {
        switch (section + "." + group + "." + object + "." + key) {
            case "contentRead.externalDocuments.outputKeys.absolutePath": return "absolute_path";
            case "contentRead.externalDocuments.outputKeys.document": return "document";
            case "contentRead.externalDocuments.outputKeys.entries": return "entries";
            case "contentRead.externalDocuments.outputKeys.excerpt": return "excerpt";
            case "contentRead.externalDocuments.outputKeys.matchStart": return "match_start";
            case "contentRead.externalDocuments.outputKeys.query": return "query";
            case "contentRead.externalDocuments.outputKeys.results": return "results";
            case "contentRead.externalDocuments.rowKeys.bodyBlobHash": return "body_blob_hash";
            case "contentRead.externalDocuments.rowKeys.content": return "content";
            case "contentRead.externalDocuments.rowKeys.contentStatus": return "content_status";
            case "contentRead.externalDocuments.rowKeys.documentId": return "document_id";
            case "contentRead.externalDocuments.rowKeys.excerpt": return "excerpt";
            case "contentRead.externalDocuments.rowKeys.matchStart": return "match_start";
            case "contentRead.readableArticle.rowKeys.bodyBlobHash": return "body_blob_hash";
            case "contentRead.readableArticle.rowKeys.content": return "content";
            case "contentRead.readableArticle.rowKeys.contentStatus": return "content_status";
            case "contentRead.readableArticle.rowKeys.id": return "id";
            case "contentRead.readableArticle.rowKeys.pdfAttachmentId": return "pdf_attachment_id";
            case "contentRead.readableArticle.rowKeys.title": return "title";
            case "contentRead.readableArticle.outputKeys.bodyBlobHash": return "body_blob_hash";
            case "contentRead.readableArticle.outputKeys.content": return "content";
            case "contentRead.readableArticle.outputKeys.contentStatus": return "content_status";
            case "contentRead.readableArticle.outputKeys.nodeId": return "node_id";
            case "contentRead.readableArticle.outputKeys.pdfAttachmentId": return "pdf_attachment_id";
            case "contentRead.readableArticle.outputKeys.title": return "title";
            case "missingResourceRead.attachmentResources.rowKeys.activeTopic": return "active_topic";
            case "missingResourceRead.attachmentResources.rowKeys.attachmentId": return "attachment_id";
            case "missingResourceRead.attachmentResources.rowKeys.availability": return "availability";
            case "missingResourceRead.attachmentResources.rowKeys.contentHash": return "content_hash";
            case "missingResourceRead.attachmentResources.rowKeys.dueReview": return "due_review";
            case "missingResourceRead.attachmentResources.rowKeys.mimeType": return "mime_type";
            case "missingResourceRead.attachmentResources.rowKeys.sizeBytes": return "size_bytes";
            case "missingResourceRead.attachmentResources.rowKeys.storageKey": return "storage_key";
            case "missingResourceRead.attachmentResources.summaryKeys.activeTopicCount": return "missing_active_topic_attachment_resource_count";
            case "missingResourceRead.attachmentResources.summaryKeys.bytes": return "missing_attachment_resource_bytes";
            case "missingResourceRead.attachmentResources.summaryKeys.count": return "missing_attachment_resource_count";
            case "missingResourceRead.attachmentResources.summaryKeys.dueReviewCount": return "missing_due_review_attachment_resource_count";
            case "missingResourceRead.attachmentResources.summaryKeys.failedBytes": return "failed_attachment_resource_bytes";
            case "missingResourceRead.attachmentResources.summaryKeys.failedCount": return "failed_attachment_resource_count";
            case "missingResourceRead.attachmentResources.summaryKeys.imageBytes": return "missing_image_attachment_resource_bytes";
            case "missingResourceRead.attachmentResources.summaryKeys.imageCount": return "missing_image_attachment_resource_count";
            case "missingResourceRead.attachmentResources.summaryKeys.otherBytes": return "missing_other_attachment_resource_bytes";
            case "missingResourceRead.attachmentResources.summaryKeys.otherCount": return "missing_other_attachment_resource_count";
            case "missingResourceRead.attachmentResources.summaryKeys.pdfBytes": return "missing_pdf_attachment_resource_bytes";
            case "missingResourceRead.attachmentResources.summaryKeys.pdfCount": return "missing_pdf_attachment_resource_count";
            case "missingResourceRead.attachmentResources.mimeCategories.imagePrefix": return "image/";
            case "missingResourceRead.attachmentResources.mimeCategories.pdfMimeType": return "application/pdf";
            case "missingResourceRead.contentBlobs.rowKeys.availability": return "availability";
            case "missingResourceRead.contentBlobs.rowKeys.sizeBytes": return "size_bytes";
            case "missingResourceRead.contentBlobs.summaryKeys.bytes": return "missing_content_blob_bytes";
            case "missingResourceRead.contentBlobs.summaryKeys.count": return "missing_content_blob_count";
            case "missingResourceRead.contentBlobs.summaryKeys.failedBytes": return "failed_content_blob_bytes";
            case "missingResourceRead.contentBlobs.summaryKeys.failedCount": return "failed_content_blob_count";
            case "resourceRead.attachmentResources.batchResponseKeys.batchToken": return "batch_token";
            case "resourceRead.attachmentResources.batchResponseKeys.failedAttachmentIds": return "failed_attachment_ids";
            case "resourceRead.attachmentResources.batchResponseKeys.syncedAttachmentIds": return "synced_attachment_ids";
            case "resourceRead.attachmentResources.resolveResponseKeys.mimeType": return "mime_type";
            case "resourceRead.attachmentResources.resolveResponseKeys.resourceUrl": return "resource_url";
            case "resourceRead.attachmentResources.resolveResponseKeys.status": return "status";
            case "resourceRead.attachmentResources.resolveStatuses.missingFile": return "missing_file";
            case "resourceRead.attachmentResources.resolveStatuses.notFound": return "not_found";
            case "resourceRead.attachmentResources.resolveStatuses.readyStatusKey": return "ready";
            case "resourceRead.attachmentResources.syncRequestKeys.attachmentId": return "attachment_id";
            case "resourceRead.attachmentResources.syncRequestKeys.contentHash": return "content_hash";
            case "resourceRead.attachmentResources.syncRequestKeys.headers": return "headers";
            case "resourceRead.attachmentResources.syncRequestKeys.url": return "url";
            case "resourceRead.attachmentResources.syncResponseKeys.attachmentId": return "attachment_id";
            case "resourceRead.attachmentResources.syncResponseKeys.availability": return "availability";
            case "resourceRead.contentBlobs.batchResponseKeys.batchToken": return "batch_token";
            case "resourceRead.contentBlobs.batchResponseKeys.databaseElapsedMs": return "db_elapsed_ms";
            case "resourceRead.contentBlobs.batchResponseKeys.failedHashes": return "failed_hashes";
            case "resourceRead.contentBlobs.batchResponseKeys.httpElapsedMs": return "http_elapsed_ms";
            case "resourceRead.contentBlobs.batchResponseKeys.parseElapsedMs": return "parse_elapsed_ms";
            case "resourceRead.contentBlobs.batchResponseKeys.syncedHashes": return "synced_hashes";
            case "resourceRead.contentBlobs.batchResponseKeys.totalElapsedMs": return "total_elapsed_ms";
            case "resourceRead.contentBlobs.syncResponseKeys.availability": return "availability";
            case "resourceRead.contentBlobs.syncResponseKeys.hash": return "hash";
            case "resourceRead.pdfPageText.outputKeys.excerpt": return "excerpt";
            case "resourceRead.pdfPageText.outputKeys.matchStart": return "match_start";
            case "resourceRead.pdfPageText.outputKeys.query": return "query";
            case "workspaceRead.snapshotShape.nestedPayload.outputKey": return "outputKey";
            case "workspaceRead.snapshotShape.nestedPayload.stateRowKey": return "stateRowKey";
            case "workspaceRead.snapshotShape.nodePayload.attachmentsOutputKey": return "attachmentsOutputKey";
            case "workspaceRead.snapshotShape.nodePayload.bodyStatusOutputKey": return "bodyStatusOutputKey";
            case "workspaceRead.snapshotShape.nodePayload.bodyStatusRowKey": return "bodyStatusRowKey";
            case "workspaceRead.snapshotShape.nodePayload.defaultKind": return "defaultKind";
            case "workspaceRead.snapshotShape.nodePayload.defaultTitle": return "defaultTitle";
            case "workspaceRead.snapshotShape.nodePayload.validKinds": return "validKinds";
            case "workspaceRead.snapshotShape.nodePayload.visibleBodyStatusGroup": return "visibleBodyStatusGroup";
            case "workspaceRead.snapshot.outputKeys.activeNodeId": return "activeNodeId";
            case "workspaceRead.snapshot.outputKeys.nodeOrder": return "nodeOrder";
            case "workspaceRead.snapshot.outputKeys.nodesById": return "nodesById";
            case "workspaceRead.snapshot.outputKeys.persistedNodeViewById": return "persistedNodeViewById";
            case "workspaceRead.snapshot.outputKeys.trashedNodeIds": return "trashedNodeIds";
            case "workspaceRead.snapshot.outputKeys.untitledSequenceByParent": return "untitledSequenceByParent";
            case "workspaceRead.snapshot.nodePayload.defaultKind": return "topic";
            case "workspaceRead.snapshot.nodePayload.defaultTitle": return "Untitled";
            case "workspaceRead.snapshot.nodePayload.bodyStatusRowKey": return "body_status";
            case "workspaceRead.snapshot.nodePayload.bodyStatusOutputKey": return "bodyStatus";
            case "workspaceRead.snapshot.nodePayload.visibleBodyStatusGroup": return "visibleBodyStatuses";
            case "workspaceRead.snapshot.nodePayload.attachmentsOutputKey": return "attachments";
            case "workspaceRead.snapshot.readingPayload.outputKey": return "reading";
            case "workspaceRead.snapshot.readingPayload.stateRowKey": return "reading_state";
            case "workspaceRead.snapshot.reviewPayload.outputKey": return "review";
            default: throw new IllegalStateException("Companion resource query descriptor is missing nested string key: " + section + "." + group + "." + object + "." + key);
        }
    }
}
