import type { MouseEvent as ReactMouseEvent } from 'react';

import type { EditorAdapter } from '../../features/editor/adapters/EditorAdapter';
import type { EditorSelection } from '../../features/editor/adapters/EditorAdapter';
import type { EditorViewportMode } from '../../features/editor/adapters/EditorAdapter';
import type { ClipboardAnchorRange } from '../../features/editor/model/anchorClipboardPayload';
import type { EditorRestoreSelectionMode } from '../../features/editor/model/editorRestoreCommand';
import type { Node, NodeAnchorLink } from '../../features/nodes/model/nodeTypes';
import type { ReviewSchedulerSettings } from '../../features/settings/model/reviewSchedulerSettings';
import type { ExternalLinkOpenRequest } from '../../shared/platform/externalLinkOpenRequest';
import type { NodeViewState } from '../../store/workspaceStore';
import type { SelectionCommandPayload } from '../contextCommands';
import type { CurrentViewTopicSnapshot } from '../currentViewTopicSnapshot';
import type { LongClozeGuardOptions } from '../hooks/editorClozeGuardrail';

import type { WorkspaceEditorContextMenu } from './WorkspaceLayout';

export interface DocumentPanelSectionProps {
  activeNodeId: string | null;
  activeVirtualNodeId?: string | null | undefined;
  isWorkspaceHydrated?: boolean;
  isTrashViewOpen?: boolean;
  isFoliolePublishedContext?: boolean;
  editableNodeId: string | null;
  canGoBack: boolean;
  canGoForward: boolean;
  canGoParent: boolean;
  contextMenu: WorkspaceEditorContextMenu | null;
  editorAdapterRef?: import('react').MutableRefObject<EditorAdapter | null>;
  editorContent: string;
  editorAppearanceKey: string;
  isEditorReadOnly: boolean;
  reviewCaretLineHighlight?: boolean;
  reviewEscapeBlurEnabled?: boolean;
  isImmersiveEditing?: boolean;
  isImmersiveMode?: boolean;
  onEnterImmersiveEdit?: () => void;
  isPriorityQuickSetActive?: boolean;
  editorNodeId: string | null;
  editorReadingRestoreCommandId?: string | null;
  editorReadingRestoreScrollTop?: number;
  editorReadingSelection?: EditorSelection | null;
  editorReadingSelectionMode?: EditorRestoreSelectionMode;
  editorReadingTargetViewportMode?: EditorViewportMode | null;
  editorReadingTargetViewportRatio?: number | null;
  editorNodeViewState?: NodeViewState | undefined;
  onBeginApplyingReadingPosition?: (selection: EditorSelection, reason: string, commandId?: string) => void;
  onCompleteApplyingReadingPosition?: (reason: string, selection?: EditorSelection, commandId?: string) => void;
  showAnswerSection: boolean;
  showDocumentOutline?: boolean;
  onAnswerChange: (answer: string) => void;
  onEditorChange: (content: string) => void;
  onEditorInput?: (meta: { contentLength?: number; nodeId: string | null }) => void;
  onEditorUndo?: () => boolean;
  onEditorRedo?: () => boolean;
  onFinalizeNodeTitle?: (nodeId: string, content: string) => void;
  onRegisterEditorDraftFlush?: (flush: (() => boolean) | null, closeFlush: (() => Promise<boolean>) | null) => void;
  onNodeContentChange: (nodeId: string, content: string, options?: { publishLocal?: boolean }) => void;
  onNodePriorityChange?: (nodeId: string, priority: number | null) => void;
  onNodeShortTermChange?: (nodeId: string, enableShortTerm: boolean | null) => void;
  onEditorContextMenu: (event: ReactMouseEvent<HTMLDivElement>) => void;
  onEditorReady: (adapter: EditorAdapter | null) => void;
  onShouldSuppressSelectionRestore?: () => boolean;
  onSetReadingPositionSelection?: (selection: EditorSelection) => void;
  onCloseContextMenu: () => void;
  onCopyImage: () => void;
  onCreateHighlight: () => void;
  onCreateNote?: (note: string) => void;
  onDeleteExistingHighlight?: () => void;
  onOpenExistingHighlight?: () => void;
  onRepairTable?: () => boolean;
  onAdjustExistingHighlightRange: (highlightNodeId: string, range: { from: number; to: number }) => boolean;
  onOpenExternalLink?: (request: ExternalLinkOpenRequest) => void;
  onPastedTextAnchors?: (payload: { anchors: ClipboardAnchorRange[]; content: string; nodeId: string }) => void;
  onCreatePdfHighlight: (selectionText: string, locator: NodeAnchorLink['locator']) => boolean;
  onCreateCloze: (options?: LongClozeGuardOptions) => void;
  onCreateClozeFromPayload?: (payload: SelectionCommandPayload, options?: LongClozeGuardOptions) => string | null;
  onCreateHighlightFromPayload?: (payload: SelectionCommandPayload) => string | null;
  onCutImage: () => void;
  onDeleteImage: () => void;
  onExportImage: () => void;
  onGoBack: () => void;
  onGoForward: () => void;
  onGoParent: () => void;
  onOpenMoveToNode?: (sourceSnapshot?: CurrentViewTopicSnapshot[]) => void;
  onSelectBreadcrumbNode: (nodeId: string) => void;
  onPersistPdfViewState: (nodeId: string, viewState: NodeViewState) => void;
  onRevealDocumentPosition: (position: number) => void;
  onRevealDocumentSelection: (selection: EditorSelection, targetViewportMode?: EditorViewportMode) => void;
  onRunDocumentCommand?: (commandId: string) => void;
  onResolveDocumentPositionAtViewportY: (clientY: number) => number | null;
  onSelectNode: (nodeId: string) => void;
  onSelectNodeInVirtualView?: (nodeId: string) => void;
  onSelectTrashNode?: ((nodeId: string) => void) | undefined;
  priorityQuickSetShortcutLabel?: string;
  reviewSchedulerSettings?: ReviewSchedulerSettings;
  nodeOrder: string[];
  trashedNodeIds: string[];
  nodesById: Record<string, Node>;
}
