export const WINDOW_TITLEBAR_CONTROLS_WIDTH = 138;
export const WINDOW_TITLEBAR_DIVIDER_WIDTH = 1;
export const WINDOW_TITLEBAR_LEADING_BUTTON_WIDTH = 32;
export const WINDOW_TITLEBAR_RIGHT_ZONE_CONTROL_GAP = 8;
export const WINDOW_TITLEBAR_RIGHT_PANEL_GAP = 6;
