import type { KeyboardEvent, MouseEvent as ReactMouseEvent, PointerEvent as ReactPointerEvent } from 'react';
import type { MutableRefObject } from 'react';

import type { EditorAdapter } from '../../features/editor/adapters/EditorAdapter';
import type { EditorSelection, EditorViewportMode } from '../../features/editor/adapters/EditorAdapter';
import type { ClipboardAnchorRange } from '../../features/editor/model/anchorClipboardPayload';
import type { ReadingPositionRestoreCommand } from '../../features/editor/model/editorRestoreCommand';
import type { Node, NodeAnchorLink } from '../../features/nodes/model/nodeTypes';
import type { ReviewSessionMode } from '../../features/review/model/reviewSessionMode';
import type { ReviewGrade, SchedulerPreviewResult } from '../../features/review/model/reviewTypes';
import type { ReviewSchedulerSettings } from '../../features/settings/model/reviewSchedulerSettings';
import type { SettingsCategoryId } from '../../features/settings/model/settingsPanelOptions';
import type {
  ExternalLibraryBrowseEntry,
  ExternalLibraryFolder
} from '../../shared/platform/externalLibraryBrowseRepository';
import type { NodeViewState } from '../../store/workspaceStore';
import type { SelectionCommandPayload } from '../contextCommands';
import type { CurrentViewTopicSnapshot } from '../currentViewTopicSnapshot';
import type { LongClozeGuardOptions } from '../hooks/editorClozeGuardrail';
import type { ReadingPositionSyncState } from '../hooks/useAppRuntime';

import type { ExternalLibrarySelection } from './externalLibraryBrowseModel';
import type { ReviewQueueVisibility } from './reviewQueueVisibility';

export interface WorkspaceEditorContextMenu {
  canRunCommands?: boolean;
  imageAttachmentId?: string;
  imageRange?: {
    from: number;
    to: number;
  };
  existingHighlight?: {
    canAdjustRange?: boolean;
    kind: 'cloze' | 'highlight';
    locator: { from: number; originalText: string; to: number };
    originalText: string;
    nodeId: string;
  };
  initialNoteOpen?: boolean;
  kind: 'image' | 'selection';
  left: number;
  mode?: 'annotation-toolbar' | 'context-menu' | 'existing-highlight-toolbar';
  notePanelLeft?: number;
  notePanelTop?: number;
  payload?: SelectionCommandPayload | null;
  repairTableAvailable?: boolean;
  tableRepairSelection?: EditorSelection | null;
  top: number;
  webLookupDocumentText?: string | null;
  webLookupPayload?: SelectionCommandPayload | null;
  webLookupTitle?: string | null;
}

export interface WorkspaceLayoutFlatProps {
  activeNodeId: string | null;
  isWorkspaceHydrated?: boolean;
  canGoBack: boolean;
  canGoForward: boolean;
  canGoParent: boolean;
  contextMenu: WorkspaceEditorContextMenu | null;
  editorAdapterRef: MutableRefObject<EditorAdapter | null>;
  editorContent: string;
  isImmersiveMode: boolean;
  isEditorReadOnly: boolean;
  isPriorityQuickSetActive: boolean;
  onNodePriorityChange: (nodeId: string, priority: number | null) => void;
  onNodeDesiredRetentionChange: (nodeId: string, desiredRetention: number | null) => void;
  onNodeShortTermChange: (nodeId: string, enableShortTerm: boolean | null) => void;
  onEnterPriorityQuickSet: () => void;
  editorNodeId: string | null;
  editorNodeViewState?: NodeViewState;
  priorityQuickSetShortcutLabel: string;
  canStartStudyMode: boolean;
  reviewDueCount: number;
  reviewPreview: SchedulerPreviewResult | null;
  isStudyMode: boolean;
  isImportManagementOpen: boolean;
  isSettingsOpen: boolean;
  requestedSettingsCategory: SettingsCategoryId | null;
  requestedSettingsDialog: 'readwise-reader' | null;
  isAnswerRevealed: boolean;
  isCurrentReviewItemGradable: boolean;
  isReviewEditing: boolean;
  reviewCurrentNodeId: string | null;
  reviewPanelQueueNodeIds: string[];
  reviewQueueNodeIds: string[];
  reviewQueueVisibility: ReviewQueueVisibility | null;
  reviewQueueCount: number;
  reviewCompletedCount: number;
  reviewStatus: 'idle' | 'awaiting-answer' | 'answer-revealed' | 'completed';
  reviewSummary: {
    completedAt: string | null;
    continueNodeId: string | null;
    createdItemCount: number;
    createdTopicCount: number;
    readingElapsedMs: number;
    readTopicCount: number;
    reviewElapsedMs: number;
    reviewedItemCount: number;
    sessionStartedAt: string | null;
  };
  reviewSessionMode: ReviewSessionMode;
  isResizingList: boolean;
  isResizingRightSidebar: boolean;
  isTrashViewOpen: boolean;
  isVirtualViewOpen: boolean;
  isExternalViewOpen: boolean;
  activeVirtualNodeId?: string | null;
  isViewingTrashNode: boolean;
  isListCollapsed: boolean;
  isRightSidebarCollapsed: boolean;
  showAnswerSection: boolean;
  listWidth: number;
  rightSidebarWidth: number;
  nodeOrder: string[];
  trashedNodeIds: string[];
  nodesById: Record<string, Node>;
  externalFolders: ExternalLibraryFolder[];
  externalEntriesByFolderId: Record<string, ExternalLibraryBrowseEntry[] | undefined>;
  externalSelection: ExternalLibrarySelection;
  nodeViewById: Record<string, NodeViewState | undefined>;
  onAnswerChange: (answer: string) => void;
  onEditorChange: (content: string) => void;
  onEditorUndo: () => boolean;
  onEditorRedo: () => boolean;
  onRegisterEditorDraftFlush: (flush: (() => boolean) | null, closeFlush: (() => Promise<boolean>) | null) => void;
  onNodeContentChange: (nodeId: string, content: string) => void;
  setNodeViewState: (nodeId: string, viewState: NodeViewState) => void;
  onEditorReady: (adapter: EditorAdapter | null) => void;
  onEditorContextMenu: (event: ReactMouseEvent<HTMLDivElement>) => void;
  onResetLayout: () => void;
  onSelectBreadcrumbNode: (nodeId: string) => void;
  onSelectNode: (nodeId: string, focusAnchor?: NodeAnchorLink | null) => void;
  onSelectNodeInVirtualView: (nodeId: string, focusAnchor?: NodeAnchorLink | null) => void;
  shouldSuppressNavigationSelectionRestore: () => boolean;
  onRevealAnchorInDocument: (anchor: NodeAnchorLink) => void;
  onPersistPdfViewState: (nodeId: string, viewState: NodeViewState) => void;
  onRevealDocumentPosition: (position: number) => void;
  onRevealDocumentSelection: (selection: EditorSelection, targetViewportMode?: EditorViewportMode) => void;
  onResolveDocumentPositionAtViewportY: (clientY: number) => number | null;
  beginApplyingReadingPosition: (selection: EditorSelection, reason: string, commandId?: string) => void;
  completeApplyingReadingPosition: (reason: string, selection?: EditorSelection, commandId?: string) => void;
  getReadingPositionRestoreCommand: () => ReadingPositionRestoreCommand | null;
  getReadingPositionSelection: () => EditorSelection | null;
  getReadingPositionSyncState: () => ReadingPositionSyncState | null;
  getReadingPositionTargetViewportMode: () => EditorViewportMode | null;
  getReadingPositionTargetViewportRatio: () => number | null;
  setReadingPositionSelection: (selection: EditorSelection) => void;
  onSelectTrashNode: (nodeId: string) => void;
  onSplitterKeyDown: (event: KeyboardEvent<HTMLDivElement>) => void;
  onSplitterPointerDown: (event: ReactPointerEvent<HTMLDivElement>) => void;
  onRightSidebarSplitterKeyDown: (event: KeyboardEvent<HTMLDivElement>) => void;
  onRightSidebarSplitterPointerDown: (event: ReactPointerEvent<HTMLDivElement>) => void;
  onOpenNotesView: () => void;
  onOpenMoveToNode: (sourceSnapshot?: CurrentViewTopicSnapshot[]) => void;
  onOpenImportManagement: () => void;
  onOpenTrashView: () => void;
  onOpenVirtualView: (nodeId?: string) => void;
  onOpenExternalSelection: (selection: ExternalLibrarySelection) => void;
  onOpenExternalLibrarySettings: () => void;
  onOpenExternalView: (folderId?: string) => void;
  onEnterImmersiveEdit: () => void;
  onEnterImmersiveMode: () => void;
  onExitImmersiveMode: () => void;
  onCloseImportManagement: () => void;
  onToggleImmersiveMode: () => void;
  onToggleListVisibility: () => void;
  onToggleRightSidebarVisibility: () => void;
  onRunImportFile: () => Promise<boolean>;
  onRunImportFolder: () => Promise<boolean>;
  onStartClipboardImport: () => boolean | Promise<boolean>;
  onGoBack: () => void;
  onGoForward: () => void;
  onGoParent: () => void;
  onCloseContextMenu: () => void;
  onCopyImage: () => void;
  onCreateHighlight: () => void;
  onCreateNote: (note: string) => void;
  onOpenSelectionNote: () => void;
  onDeleteExistingHighlight: () => void;
  onOpenExistingHighlight: () => void;
  onRepairTable: () => boolean;
  onAdjustExistingHighlightRange: (highlightNodeId: string, range: { from: number; to: number }) => boolean;
  onCreateSelectionHighlight: (payload: SelectionCommandPayload) => string | null;
  onPastedTextAnchors?: (payload: { anchors: ClipboardAnchorRange[]; content: string; nodeId: string }) => void;
  onToggleSelectionHighlight: (payload: SelectionCommandPayload) => 'created' | 'deleted' | null;
  onCreateSelectionNote: (payload: SelectionCommandPayload, note?: string) => string | null;
  onCreatePdfHighlight: (selectionText: string, locator: NodeAnchorLink['locator']) => boolean;
  onCreateCloze: (options?: LongClozeGuardOptions) => void;
  onCreateClozeFromPayload?: (payload: SelectionCommandPayload, options?: LongClozeGuardOptions) => string | null;
  onCreateHighlightFromPayload?: (payload: SelectionCommandPayload) => string | null;
  onCutImage: () => void;
  onDeleteImage: () => void;
  onExportImage: () => void;
  onStartStudyMode: () => void;
  onToggleReviewSession: () => void;
  onOpenSettings: () => void;
  onRunRailAction?: (commandId: string) => void;
  onCloseSettings: () => void;
  onRevealAnswer: () => void;
  onGradeReview: (grade: ReviewGrade) => Promise<boolean>;
  onCompleteReviewItem: () => Promise<boolean>;
  onDeferReviewItem: () => Promise<boolean>;
  onDismissReviewItem: () => Promise<boolean>;
  onSoonReviewItem: () => Promise<boolean>;
  onContinueReading: () => void;
  onResumeReviewItem: () => void;
  onExitReviewMode: () => void;
  onSetReviewSessionMode: (mode: ReviewSessionMode) => void;
  reviewSchedulerSettings: ReviewSchedulerSettings;
  selectedTrashNodeId: string | null;
}
