import { MANAGED_INBOX_APP_SETTING_KEY } from '../../../lib/platform/managedInbox.js';

export const APP_SETTINGS_STORAGE_KEYS = {
  markdownSyntaxVisibility: 'foliole-markdown-syntax-visibility',
  highlightAnnotationPrefix: 'foliole-highlight-annotation-prefix',
  longClozeFrontGuardMode: 'foliole-long-cloze-front-guard-mode',
  longClozeFrontGuardSelectionMin: 'foliole-long-cloze-front-guard-selection-min',
  longClozeFrontGuardFrontMax: 'foliole-long-cloze-front-guard-front-max',
  autoLocalizeRemoteImages: 'foliole-auto-localize-remote-images',
  editorDisplayMode: 'foliole-editor-display-mode',
  settingsActiveCategory: 'foliole-settings-active-category',
  workspaceRailItems: 'foliole-workspace-rail-items',
  uiFont: 'foliole-ui-font-preset',
  customUiFont: 'foliole-custom-ui-font-family',
  interfaceFont: 'foliole-interface-font-preset',
  monospaceFont: 'foliole-monospace-font-preset',
  baseColor: 'foliole-base-color',
  pdfReadingMode: 'foliole-pdf-reading-mode',
  readingLineHeight: 'foliole-reading-line-height',
  readingContentWidth: 'foliole-reading-content-width',
  dimImagesInDarkMode: 'foliole-dim-images-in-dark-mode',
  fontColor: 'foliole-font-color',
  accentColor: 'foliole-accent-color',
  selectionColor: 'foliole-selection-color',
  highlightColor: 'foliole-highlight-color',
  clozeColor: 'foliole-cloze-color',
  fontColorDark: 'foliole-font-color-dark',
  accentColorDark: 'foliole-accent-color-dark',
  selectionColorDark: 'foliole-selection-color-dark',
  highlightColorDark: 'foliole-highlight-color-dark',
  clozeColorDark: 'foliole-cloze-color-dark',
  workspaceSurfacePalette: 'foliole-workspace-surface-palette',
  workspaceSurfaceAssignments: 'foliole-workspace-surface-assignments',
  workspaceSurfacePaletteDark: 'foliole-workspace-surface-palette-dark',
  workspaceSurfaceAssignmentsDark: 'foliole-workspace-surface-assignments-dark',
  workspaceSurfaceGeneratorMode: 'foliole-workspace-surface-generator-mode',
  workspaceSurfaceRecommendationId: 'foliole-workspace-surface-recommendation-id',
  workspaceSurfaceAutoSeed: 'foliole-workspace-surface-auto-seed',
  workspaceSurfaceAutoOptions: 'foliole-workspace-surface-auto-options',
  workspaceSurfaceRandomHistory: 'foliole-workspace-surface-random-history',
  workspaceSurfaceFavorites: 'foliole-workspace-surface-favorites',
  workspaceSurfaceGeneratorModeDark: 'foliole-workspace-surface-generator-mode-dark',
  workspaceSurfaceRecommendationIdDark: 'foliole-workspace-surface-recommendation-id-dark',
  workspaceSurfaceAutoSeedDark: 'foliole-workspace-surface-auto-seed-dark',
  workspaceSurfaceAutoOptionsDark: 'foliole-workspace-surface-auto-options-dark',
  workspaceSurfaceRandomHistoryDark: 'foliole-workspace-surface-random-history-dark',
  workspaceSurfaceFavoritesDark: 'foliole-workspace-surface-favorites-dark',
  interfaceFontSize: 'foliole-interface-font-size',
  customInterfaceFont: 'foliole-custom-interface-font-family',
  customMonospaceFont: 'foliole-custom-monospace-font-family',
  mouseGestureLeftAction: 'foliole-mouse-gesture-left-action',
  mouseGestureRightAction: 'foliole-mouse-gesture-right-action',
  mouseGestureLeftUpAction: 'foliole-mouse-gesture-left-up-action',
  mouseGestureLeftDownAction: 'foliole-mouse-gesture-left-down-action',
  mouseGestureTrailColor: 'foliole-mouse-gesture-trail-color',
  mouseGestureTrailLineWidth: 'foliole-mouse-gesture-trail-line-width',
  mouseGestureTrailOpacity: 'foliole-mouse-gesture-trail-opacity',
  mouseGestureSegmentThreshold: 'foliole-mouse-gesture-segment-threshold',
  mouseGestureTrailPointThreshold: 'foliole-mouse-gesture-trail-point-threshold',
  nodeIconPrimarySvg: 'foliole-node-icon-primary-svg',
  nodeIconSecondarySvg: 'foliole-node-icon-secondary-svg',
  nodeIconPrimaryLucideIcon: 'foliole-node-icon-primary-lucide-icon',
  nodeIconSecondaryLucideIcon: 'foliole-node-icon-secondary-lucide-icon',
  nodeIconPrimaryAppearance: 'foliole-node-icon-primary-appearance',
  nodeIconSecondaryAppearance: 'foliole-node-icon-secondary-appearance',
  nodeIconReviewVariantMode: 'foliole-node-icon-review-variant-mode',
  nodeIconPendingStrokeStyle: 'foliole-node-icon-pending-stroke-style',
  nodeIconScheduledStrokeStyle: 'foliole-node-icon-scheduled-stroke-style',
  nodeIconDismissedStrokeStyle: 'foliole-node-icon-dismissed-stroke-style',
  nodeIconPendingDashLength: 'foliole-node-icon-pending-dash-length',
  nodeIconScheduledDashLength: 'foliole-node-icon-scheduled-dash-length',
  nodeIconDismissedDashLength: 'foliole-node-icon-dismissed-dash-length',
  nodeIconPendingGapLength: 'foliole-node-icon-pending-gap-length',
  nodeIconScheduledGapLength: 'foliole-node-icon-scheduled-gap-length',
  nodeIconDismissedGapLength: 'foliole-node-icon-dismissed-gap-length',
  nodeIconPendingLineWidth: 'foliole-node-icon-pending-line-width',
  nodeIconScheduledLineWidth: 'foliole-node-icon-scheduled-line-width',
  nodeIconDismissedLineWidth: 'foliole-node-icon-dismissed-line-width',
  nodeIconPendingColor: 'foliole-node-icon-pending-color',
  nodeIconScheduledColor: 'foliole-node-icon-scheduled-color',
  nodeIconDismissedColor: 'foliole-node-icon-dismissed-color',
  nodeIconDismissedFadeEnabled: 'foliole-node-icon-dismissed-fade-enabled',
  nodeIconDismissedFadeOpacity: 'foliole-node-icon-dismissed-fade-opacity',
  nodeIconDismissedFadeWholeRow: 'foliole-node-icon-dismissed-fade-whole-row',
  nodeIconPendingTopicAppearance: 'foliole-node-icon-pending-topic-appearance',
  nodeIconPendingItemAppearance: 'foliole-node-icon-pending-item-appearance',
  nodeIconScheduledTopicAppearance: 'foliole-node-icon-scheduled-topic-appearance',
  nodeIconScheduledItemAppearance: 'foliole-node-icon-scheduled-item-appearance',
  nodeIconDismissedTopicAppearance: 'foliole-node-icon-dismissed-topic-appearance',
  nodeIconDismissedItemAppearance: 'foliole-node-icon-dismissed-item-appearance',
  nodeListRowSpacing: 'foliole-node-list-row-spacing',
  nodeListManualCollapsed: 'foliole-node-list-manual-collapsed',
  nodeListManualExpanded: 'foliole-node-list-manual-expanded',
  nodeTrashManualCollapsed: 'foliole-node-trash-manual-collapsed',
  workspaceContentSort: 'foliole-workspace-content-sort',
  externalLibraryCollapsed: 'foliole-external-library-collapsed',
  externalLibraryFolderOrder: 'foliole-external-library-folder-order',
  listCollapsed: 'foliole-workspace-list-collapsed',
  listWidth: 'foliole-workspace-list-width',
  dualListWidth: 'foliole-workspace-dual-list-width',
  virtualSectionHeight: 'foliole-workspace-virtual-section-height',
  externalSectionHeight: 'foliole-workspace-external-section-height',
  documentWidth: 'foliole-workspace-document-width',
  linkPanelSize: 'foliole-link-panel-size',
  externalDocumentPreviewPanelSize: 'foliole-external-document-preview-panel-size',
  rightSidebarCollapsed: 'foliole-workspace-right-sidebar-collapsed',
  rightSidebarWidth: 'foliole-workspace-right-sidebar-width',
  rightSidebarActivePanel: 'foliole-workspace-right-sidebar-active-panel',
  rightSidebarPanelOrder: 'foliole-workspace-right-sidebar-panel-order',
  importManagementActivePage: 'foliole-import-management-active-page',
  managedInboxPath: MANAGED_INBOX_APP_SETTING_KEY,
  commandRecents: 'foliole-command-recents',
  nodePaletteRecents: 'foliole-node-palette-recents',
  commandShortcutOverrides: 'foliole-command-shortcut-overrides',
  desktopDeviceSyncEnabled: 'foliole-desktop-device-sync-enabled'
} as const;

export const APP_SETTINGS_OPTIONS = {
  markdownSyntaxVisibility: ['hidden', 'visible'] as const,
  editorDisplayMode: ['preview', 'source'] as const,
  pdfReadingMode: ['original', 'inverted', 'warm'] as const,
  readingLineHeight: ['compact', 'standard', 'relaxed'] as const
} as const;

export type MarkdownSyntaxVisibility = (typeof APP_SETTINGS_OPTIONS.markdownSyntaxVisibility)[number];
export type EditorDisplayMode = (typeof APP_SETTINGS_OPTIONS.editorDisplayMode)[number];
export type PdfReadingMode = (typeof APP_SETTINGS_OPTIONS.pdfReadingMode)[number];
export type ReadingLineHeight = (typeof APP_SETTINGS_OPTIONS.readingLineHeight)[number];

export interface PersistedAppSettings {
  autoLocalizeRemoteImages: boolean;
  markdownSyntaxVisibility: MarkdownSyntaxVisibility;
  editorDisplayMode: EditorDisplayMode;
}

export const DEFAULT_PERSISTED_APP_SETTINGS: PersistedAppSettings = {
  autoLocalizeRemoteImages: true,
  markdownSyntaxVisibility: 'hidden',
  editorDisplayMode: 'preview'
};
