#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
WINDOWS_WORKDIR="${WINDOWS_WORKDIR:-C:\\dev\\foliole}"
WINDOWS_DESKTOP_TEST_SYNC_SCRIPT="${WINDOWS_DESKTOP_TEST_SYNC_SCRIPT:-scripts/windows/windows-sync.sh}"
WINDOWS_DESKTOP_TEST_BUILD_COMMAND="${WINDOWS_DESKTOP_TEST_BUILD_COMMAND:-npm.cmd run build}"
WINDOWS_DESKTOP_TEST_COMPILE_COMMAND="${WINDOWS_DESKTOP_TEST_COMPILE_COMMAND:-npm.cmd run electron:compile}"
WINDOWS_DESKTOP_TEST_RUNNER="${WINDOWS_DESKTOP_TEST_RUNNER:-${SCRIPT_DIR}/run-playwright-desktop.ps1}"
WINDOWS_DESKTOP_TEST_CONFIG="${WINDOWS_DESKTOP_TEST_CONFIG:-playwright.desktop.config.ts}"
WINDOWS_DESKTOP_TEST_POWERSHELL_BIN="${WINDOWS_DESKTOP_TEST_POWERSHELL_BIN:-powershell.exe}"
WINDOWS_DESKTOP_TEST_SKIP_BUILD="${WINDOWS_DESKTOP_TEST_SKIP_BUILD:-}"
WINDOWS_DESKTOP_TEST_SKIP_SYNC="${WINDOWS_DESKTOP_TEST_SKIP_SYNC:-}"

cd "${REPO_ROOT}"

if [[ -z "${WINDOWS_DESKTOP_TEST_SKIP_SYNC}" ]]; then
  bash "${WINDOWS_DESKTOP_TEST_SYNC_SCRIPT}"
fi

PS_SCRIPT_WIN_PATH="$(wslpath -w "${WINDOWS_DESKTOP_TEST_RUNNER}")"
echo "[windows-desktop-test] workdir=${WINDOWS_WORKDIR}"
echo "[windows-desktop-test] config=${WINDOWS_DESKTOP_TEST_CONFIG}"
"${WINDOWS_DESKTOP_TEST_POWERSHELL_BIN}" \
  -NoProfile \
  -ExecutionPolicy Bypass \
  -File "${PS_SCRIPT_WIN_PATH}" \
  -WindowsWorkDir "${WINDOWS_WORKDIR}" \
  -Config "${WINDOWS_DESKTOP_TEST_CONFIG}" \
  -BuildCommand "${WINDOWS_DESKTOP_TEST_BUILD_COMMAND}" \
  -CompileCommand "${WINDOWS_DESKTOP_TEST_COMPILE_COMMAND}" \
  $( [[ -n "${WINDOWS_DESKTOP_TEST_SKIP_BUILD}" ]] && printf '%s' '-SkipBuild' ) \
  "$@"
