import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  DEFAULT_APPEARANCE_COLORS,
  deriveMutedForegroundRgb,
  getClozeSurfaceAlpha,
  getHighlightSurfaceAlpha,
  getSelectionSurfaceAlpha,
  hexColorToRgbChannels,
  type AppearanceDefaultColorMode
} from '../src/shared/config/defaultAppearanceColors.ts';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = path.join(repoRoot, 'src/app/generated/appearance-colors.css');

function selectionForegroundColor(mode: AppearanceDefaultColorMode) {
  return mode === 'dark' ? '#ffffff' : 'rgb(var(--color-foreground))';
}

function textSelectionBackgroundColor(mode: AppearanceDefaultColorMode) {
  return mode === 'dark'
    ? 'color-mix(in srgb, var(--app-selection-color) 50%, rgb(var(--color-background)) 50%)'
    : `rgb(var(--app-selection-color-rgb) / ${getSelectionSurfaceAlpha(mode)})`;
}

function renderColorVariables(mode: AppearanceDefaultColorMode) {
  const colors = DEFAULT_APPEARANCE_COLORS[mode];
  const accentRgb = hexColorToRgbChannels(colors.accent);
  const clozeRgb = hexColorToRgbChannels(colors.cloze);
  const fontRgb = hexColorToRgbChannels(colors.font);
  const highlightRgb = hexColorToRgbChannels(colors.highlight);
  const selectionRgb = hexColorToRgbChannels(colors.selection);

  return [
    `  --color-foreground: ${fontRgb};`,
    `  --color-muted-foreground: ${deriveMutedForegroundRgb(fontRgb, mode)};`,
    `  --app-accent-color: ${colors.accent};`,
    `  --app-accent-color-rgb: ${accentRgb};`,
    `  --app-selection-color: ${colors.selection};`,
    `  --app-selection-color-rgb: ${selectionRgb};`,
    `  --app-text-selection-bg-color: ${textSelectionBackgroundColor(mode)};`,
    `  --app-text-selection-fg-color: ${selectionForegroundColor(mode)};`,
    `  --app-selection-foreground-color: ${selectionForegroundColor(mode)};`,
    `  --app-selection-surface-color: rgb(var(--app-selection-color-rgb) / ${getSelectionSurfaceAlpha(mode)});`,
    `  --app-highlight-color: ${colors.highlight};`,
    `  --app-highlight-color-rgb: ${highlightRgb};`,
    `  --app-highlight-surface-color: rgb(var(--app-highlight-color-rgb) / ${getHighlightSurfaceAlpha(mode)});`,
    `  --app-cloze-color: ${colors.cloze};`,
    `  --app-cloze-color-rgb: ${clozeRgb};`,
    `  --app-cloze-surface-color: rgb(var(--app-cloze-color-rgb) / ${getClozeSurfaceAlpha(mode)});`
  ].join('\n');
}

function renderCss() {
  return [
    '/* This file is generated by scripts/generate-appearance-colors.ts. */',
    ':root {',
    renderColorVariables('light'),
    '}',
    '',
    ":root[data-resolved-base-color='dark'] {",
    renderColorVariables('dark'),
    '}',
    ''
  ].join('\n');
}

async function main() {
  const nextContent = renderCss();

  if (process.argv.includes('--check')) {
    const currentContent = await readFile(outputPath, 'utf8');
    if (currentContent !== nextContent) {
      throw new Error(`${path.relative(repoRoot, outputPath)} is out of date. Run npm run appearance:colors:generate.`);
    }
    return;
  }

  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, nextContent);
}

await main();
